package com.ssl.module.base.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ssl.module.base.db.BillItem;
import com.ssl.module.base.db.BillType;
import com.ssl.module.base.db.Password;

import com.ssl.module.base.db.BillItemDao;
import com.ssl.module.base.db.BillTypeDao;
import com.ssl.module.base.db.PasswordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig billItemDaoConfig;
    private final DaoConfig billTypeDaoConfig;
    private final DaoConfig passwordDaoConfig;

    private final BillItemDao billItemDao;
    private final BillTypeDao billTypeDao;
    private final PasswordDao passwordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        billItemDaoConfig = daoConfigMap.get(BillItemDao.class).clone();
        billItemDaoConfig.initIdentityScope(type);

        billTypeDaoConfig = daoConfigMap.get(BillTypeDao.class).clone();
        billTypeDaoConfig.initIdentityScope(type);

        passwordDaoConfig = daoConfigMap.get(PasswordDao.class).clone();
        passwordDaoConfig.initIdentityScope(type);

        billItemDao = new BillItemDao(billItemDaoConfig, this);
        billTypeDao = new BillTypeDao(billTypeDaoConfig, this);
        passwordDao = new PasswordDao(passwordDaoConfig, this);

        registerDao(BillItem.class, billItemDao);
        registerDao(BillType.class, billTypeDao);
        registerDao(Password.class, passwordDao);
    }
    
    public void clear() {
        billItemDaoConfig.clearIdentityScope();
        billTypeDaoConfig.clearIdentityScope();
        passwordDaoConfig.clearIdentityScope();
    }

    public BillItemDao getBillItemDao() {
        return billItemDao;
    }

    public BillTypeDao getBillTypeDao() {
        return billTypeDao;
    }

    public PasswordDao getPasswordDao() {
        return passwordDao;
    }

}
